/* End-to-end client delivery process. Document records remain the source of truth. */
(function(){
const find=id=>db.documents.find(d=>d.id===id);
function related(q,type){return db.documents.find(d=>d.type===type&&d.status!=='Cancelled'&&(d.rootId===q.id||d.sourceId===q.id))}
function stage(q){const p=related(q,'Proforma'),i=related(q,'Invoice');if(i&&totals(i).balance<=0)return 7;if(i)return 6;if(p&&totals(p).paid>=totals(p).total)return 5;if(p)return 4;if(q.contractConfirmedAt)return 3;if(q.status==='Accepted')return 2;if(q.status==='Sent')return 1;return 0;}
function reconcile(){let changed=false;for(const q of db.documents.filter(d=>d.type==='Quotation'&&d.clientApprovedForProcess&&d.contractConfirmedAt)){const before=db.documents.length;ClientProcessEngine.prepare(db,q,uid);changed ||= before!==db.documents.length;}if(changed)persist();}
const names=['Quotation draft','Quotation sent','Quotation approved','Contract confirmed','50% advance due','Work in progress','Final payment due','Completed'];
function docActions(d){return `<button onclick="showPreview('${d.id}')">Preview</button><button onclick="openDoc('${d.id}')">Edit / payment</button><button onclick="processShare('${d.id}','whatsapp')">WhatsApp</button><button onclick="processShare('${d.id}','email')">Email</button>`;}
function receiptActions(d){return (d?.payments||[]).map((p,n)=>`<div class="totalrow"><span>Receipt · ${esc(p.date)} · ${esc(fmt(d,p.amount))}</span><span><button onclick="processShare('${d.id}','download',${n})">Download receipt</button><button onclick="processShare('${d.id}','whatsapp',${n})">WhatsApp</button><button onclick="processShare('${d.id}','email',${n})">Email</button></span></div>`).join('');}
window.clientProcessPage=()=>{reconcile();const quotes=db.documents.filter(d=>d.type==='Quotation'&&d.status!=='Cancelled');return pageHeader('Client process',`<button onclick="newDoc('Quotation')">+ New quotation</button><button onclick="refreshWorkspaceIfChanged()">Refresh approvals</button>`,'Quotation → approval → contract confirmation → 50% advance → delivery → final payment. Share documents manually.')+quotes.map(q=>{const p=related(q,'Proforma'),i=related(q,'Invoice'),s=stage(q);return `<section class="panel"><h2>${esc(q.client?.name||'Client')} · ${esc(q.project||q.number)}</h2><p>${names.map((n,k)=>`<span class="badge ${k===s?'Paid':''}">${k+1}. ${n}</span>`).join(' → ')}</p><h3>Quotation ${esc(q.number)}</h3><div class="actions">${docActions(q)}${q.status==='Draft'?`<button onclick="processMarkSent('${q.id}')">Mark quotation sent</button>`:''}${q.status==='Sent'?`<button onclick="processRecordApproval('${q.id}')">Record quotation approval</button>`:''}</div>${q.status==='Accepted'?'<p>Quotation approval received.</p>':''}${q.status==='Accepted'&&!q.contractConfirmedAt?`<button class="primary" onclick="processContract('${q.id}')">Complete contract confirmation</button><p class="hint">Complete the contract form before the 50% advance proforma is created.</p>`:''}${q.contractConfirmedAt?`<p><b>Contract confirmed</b> · ${esc(q.contract?.acceptedBy||'Client')} · ${esc(q.contract?.startDate||'Start date to be agreed')}</p>`:''}${p?`<h3>Proforma ${esc(p.number)} · 50% advance ${esc(fmt(p,totals(p).total))}</h3><div class="actions">${docActions(p)}</div>${receiptActions(p)}`:''}${s===5&&!i?`<button class="primary" onclick="processComplete('${q.id}')">Work complete — prepare final invoice</button>`:''}${i?`<h3>Final invoice ${esc(i.number)} · Balance ${esc(fmt(i,totals(i).balance))}</h3><div class="actions">${docActions(i)}</div>${receiptActions({...i,payments:i.payments})}`:''}</section>`}).join('')+(quotes.length?'':'<section class="panel">Create a quotation to begin a client process.</section>');};
window.processMarkSent=id=>{commitChange(()=>{find(id).status='Sent';find(id).updated=new Date().toISOString()},'Quotation marked sent. Record approval after the client accepts it.');};
window.processRecordApproval=id=>{commitChange(()=>{const q=find(id);q.status='Accepted';q.clientApprovedForProcess=true;q.acceptedAt=new Date().toISOString();q.updated=q.acceptedAt},'Quotation approval recorded. Complete the contract confirmation next.');};
window.processContract=id=>{const q=find(id);if(!q||q.status!=='Accepted')return toast('Record quotation approval first.');modal('Contract confirmation',`<div class="full"><label>Client / authorised signatory<input id="contractAcceptedBy" required value="${esc(q.client?.name||'')}"></label></div><div><label>Contract start date<input id="contractStart" type="date" required value="${esc(q.contract?.startDate||new Date().toISOString().slice(0,10))}"></label></div><div><label>Expected completion date<input id="contractCompletion" type="date" value="${esc(q.contract?.completionDate||'')}"></label></div><div class="full"><label>Confirmed scope / notes<textarea id="contractScope" required>${esc(q.contract?.scope||q.project||'Services as quoted')}</textarea></label></div><div class="full"><label><input id="contractConfirmation" type="checkbox" required> I confirm the agreed scope, dates, and 50% advance requirement.</label></div>`,()=>{const acceptedBy=document.getElementById('contractAcceptedBy').value.trim(),startDate=document.getElementById('contractStart').value,completionDate=document.getElementById('contractCompletion').value,scope=document.getElementById('contractScope').value.trim();if(!acceptedBy||!startDate||!scope)return;commitChange(()=>{q.contract={acceptedBy,startDate,completionDate,scope};q.contractConfirmedAt=new Date().toISOString();q.updated=q.contractConfirmedAt;ClientProcessEngine.prepare(db,q,uid)},'Contract confirmed and 50% advance proforma created.');closeRecord();nav('Client Process')});};
window.processComplete=id=>{const q=find(id),p=related(q,'Proforma');if(!p||totals(p).paid<totals(p).total)return toast('Record the 50% advance first.');if(related(q,'Invoice'))return openDoc(related(q,'Invoice').id);openDoc(p.id);convertTo('Invoice');if(draft?.type==='Invoice'&&saveDoc(true)){q.workCompletedAt=new Date().toISOString();persist();draft=null;nav('Client Process');}};
window.processShare=async(id,channel,index)=>{const d=find(id);if(!d)return;try{const receipt=Number.isInteger(index),payment=receipt?d.payments[index]:null;const file=receipt?await createPaymentReceiptPdf({...d,payments:[payment],number:d.number+'-R'+(index+1)}):await createDocumentPdf(d);downloadPdfFile(file);if(channel==='download')return;const title=(receipt?'Payment receipt':docLabel(d.type))+' '+d.number;const message=title+' for '+(d.client?.name||'your project')+'. Please find the PDF attached.';if(channel==='whatsapp'){let phone=String(d.client?.phone||'').replace(/\D/g,'');if(phone.length===10)phone='91'+phone;window.open('https://wa.me/'+phone+'?text='+encodeURIComponent(message),'_blank','noopener');}else{location.href='mailto:'+encodeURIComponent(d.client?.email||'')+'?subject='+encodeURIComponent(title)+'&body='+encodeURIComponent(message);}toast('PDF downloaded. Attach it to the message and send manually.');}catch(e){toast(e.message||'Could not prepare the document.')}};
HORIZONTAL_MORE_SECTIONS.push('Client Process');HORIZONTAL_MORE_GROUPS[1].items.push('Client Process');
const previous=render;render=function(){previous();if(view==='Client Process'&&!draft)document.getElementById('app').innerHTML=clientProcessPage();const navEl=document.getElementById('nav');if(navEl&&!navEl.querySelector('[data-client-process]')){const button=document.createElement('button');button.dataset.clientProcess='1';button.textContent='Client Process';button.onclick=()=>nav('Client Process');navEl.append(button);}};
document.addEventListener('erp-workspace-loaded',()=>{if(!draft)reconcile()});
})();
