'use strict';
/* Stable CRM core: one renderer and one document workflow. */
function migrate(data){const state=data&&typeof data==='object'?data:{};state.version=2;for(const key of ['documents','clients','services','tasks','projects','activity'])state[key]=Array.isArray(state[key])?state[key].filter(x=>x&&typeof x==='object'):[];state.settings={...structuredClone(defaults.settings),...(state.settings||{})};state.sequences=state.sequences&&typeof state.sequences==='object'?state.sequences:{};state.documents=state.documents.map(d=>({...d,type:['Quotation','Proforma','Invoice'].includes(d.type)?d.type:'Quotation',client:{name:'',contact:'',email:'',phone:'',address:'',gstin:'',...(d.client||{})},items:Array.isArray(d.items)?d.items.filter(i=>i&&typeof i==='object'):[],payments:Array.isArray(d.payments)?d.payments.filter(p=>p&&typeof p==='object'):[],currency:d.currency==='AED'?'AED':'INR',discount:num(d.discount),tax:Number.isFinite(+d.tax)?+d.tax:+state.settings.tax,status:d.status||'Draft'}));return state}
db=migrate(db);
const stableMoney=(d,v)=>`${d?.currency==='AED'?'AED':'INR'} ${Number(v||0).toLocaleString(d?.currency==='AED'?'en-AE':'en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
totals=d=>{const subtotal=(d.items||[]).reduce((s,i)=>s+num(i.qty||1)*num(i.rate),0),discount=subtotal*num(d.discount)/100,net=subtotal-discount,tax=net*num(d.tax)/100,total=net+tax,paid=(d.payments||[]).reduce((s,p)=>s+num(p.amount),0);return {subtotal,discount,tax,total,paid,balance:Math.max(0,total-paid)}};
status=d=>d.status==='Cancelled'?'Cancelled':d.type==='Invoice'?(totals(d).balance<=0&&totals(d).total?'Paid':totals(d).paid?'Part paid':d.status==='Sent'&&d.due<today()?'Overdue':d.status):d.status;
const typeLabel=t=>t==='Invoice'?'Final invoice':t==='Proforma'?'Proforma invoice':'Quotation';
const typeView=t=>t==='Invoice'?'Invoices':t==='Proforma'?'Proformas':'Quotations';
function stablePersist(){migrate(db);return persist()}
function stableNav(next){if(draft&&!confirm('Leave this document? Unsaved changes will be lost.'))return;draft=null;view=next;query='';filter='';render()}
nav=stableNav;
function nextNumber(type){const prefix=type==='Invoice'?'ED-':type==='Proforma'?'ED-P-':'ED-Q-';const max=Math.max(0,...db.documents.filter(d=>d.number?.startsWith(prefix)).map(d=>+String(d.number).slice(prefix.length)||0));return prefix+String(max+1).padStart(4,'0')}
function page(title,actions='',sub=''){return `<header><div><div class="eyebrow">ERIC'S DESIGNS / ${esc(view)}</div><h1>${esc(title)}</h1>${sub?`<p class="sub">${esc(sub)}</p>`:''}</div><div class="actions">${actions}</div></header>`}
function render(){const navEl=document.getElementById('nav');if(navEl)navEl.innerHTML=['Overview','Documents','Clients','Projects','Follow-ups','Services','Settings'].map(x=>`<button title="${x}" class="${view===x?'active':''}" onclick="nav('${x}')">${x}</button>`).join('');const app=document.getElementById('app');if(!app)return;if(draft){app.innerHTML=editor();updateTotal();return}app.innerHTML=view==='Overview'?dashboard():view==='Documents'||['Quotations','Proformas','Invoices'].includes(view)?documents():view==='Clients'?clients():view==='Projects'?projects():view==='Follow-ups'?followups():view==='Services'?services():settings()}
function dashboard(){const inv=db.documents.filter(d=>d.type==='Invoice'),out=inv.reduce((s,d)=>s+totals(d).balance,0),paid=inv.reduce((s,d)=>s+totals(d).paid,0);return page('Dashboard',`<button onclick="newDoc('Quotation')">+ Quotation</button><button class="primary" onclick="newDoc('Invoice')">+ Invoice</button>`,'Clients, documents, payments, and follow-ups.')+`<div class="stats four"><div class="stat"><span>Clients</span><strong>${db.clients.length}</strong></div><div class="stat"><span>Outstanding</span><strong>INR ${out.toLocaleString('en-IN',{minimumFractionDigits:2})}</strong></div><div class="stat"><span>Received</span><strong>INR ${paid.toLocaleString('en-IN',{minimumFractionDigits:2})}</strong></div><div class="stat"><span>Open follow-ups</span><strong>${db.tasks.filter(t=>!t.done).length}</strong></div></div><section class="panel"><h2>Recent documents</h2>${documentRows(db.documents.slice().sort((a,b)=>String(b.updated||'').localeCompare(String(a.updated||''))).slice(0,8))}</section>`}
function documents(){const list=db.documents.filter(d=>(view==='Documents'||typeView(d.type)===view)&&(!query||[d.number,d.client?.name,d.project].join(' ').toLowerCase().includes(query.toLowerCase())));return page(view==='Documents'?'Documents':view,`<button onclick="newDoc('Quotation')">+ Quotation</button><button onclick="newDoc('Proforma')">+ Proforma</button><button class="primary" onclick="newDoc('Invoice')">+ Invoice</button>`,'Create, edit, preview, and download every document.')+`<section class="panel"><div class="toolbar"><input placeholder="Search documents or clients" oninput="query=this.value;render()"></div>${documentRows(list)}</section>`}
function documentRows(list){return list.length?`<div class="tablewrap"><table><thead><tr><th>Document</th><th>Client</th><th>Project</th><th>Status</th><th class="right">Total</th><th></th></tr></thead><tbody>${list.map(d=>`<tr><td><b>${esc(d.number)}</b><small>${typeLabel(d.type)}</small></td><td>${esc(d.client?.name)}</td><td>${esc(d.project||'-')}</td><td><span class="badge">${esc(status(d))}</span></td><td class="right">${stableMoney(d,totals(d).total)}</td><td><div class="actions"><button onclick="editDocument('${d.id}')">Edit</button><button onclick="showPreview('${d.id}')">Preview</button></div></td></tr>`).join('')}</tbody></table></div>`:`<div class="empty"><h2>No documents yet.</h2><button class="primary" onclick="newDoc('Quotation')">Create quotation</button></div>`}
function newDoc(type){draft={id:uid(),type,number:nextNumber(type),date:today(),due:addDays(type==='Invoice'?7:30),status:'Draft',currency:'INR',project:'',discount:0,tax:num(db.settings.tax),client:{name:'',contact:'',email:'',phone:'',address:'',gstin:''},items:[{name:'',description:'',qty:1,rate:0}],payments:[],terms:type==='Proforma'?'Proforma invoice for the proposed services. This is not a final invoice or payment receipt.\n'+db.settings.quoteTerms:type==='Invoice'?db.settings.invoiceTerms:db.settings.quoteTerms,business:structuredClone(db.settings)};view=typeView(type);render()}
function editDocument(id){const record=db.documents.find(d=>d.id===id);if(!record){toast('Document not found.');return}draft=structuredClone(record);view=typeView(draft.type);document.getElementById('preview')?.close();render()}
openDoc=editDocument;
function editor(){const d=draft;return page(`${typeLabel(d.type)} ${d.number}`,`<button onclick="cancelEdit()">Back</button><button onclick="previewDraft()">Preview</button><button class="primary" onclick="saveDoc()">Save</button>`)+`<div class="editor"><div class="stack"><section class="panel"><h2>Document details</h2><div class="grid three">${input('Number','doc-number',d.number)}${input('Issue date','doc-date',d.date,'date')}${input(d.type==='Invoice'?'Due date':'Valid until','doc-due',d.due,'date')}${input('Project','doc-project',d.project)}<div><label>Currency<select id="doc-currency"><option ${d.currency==='INR'?'selected':''}>INR</option><option ${d.currency==='AED'?'selected':''}>AED</option></select></label></div><div><label>Status<select id="doc-status">${['Draft','Sent','Accepted','Declined','Cancelled'].map(x=>`<option ${d.status===x?'selected':''}>${x}</option>`).join('')}</select></label></div></div></section><section class="panel"><h2>Client</h2><div class="grid">${input('Client / company','client-name',d.client.name)}${input('Contact','client-contact',d.client.contact)}${input('Email','client-email',d.client.email)}${input('Phone','client-phone',d.client.phone)}${input('Address','client-address',d.client.address)}</div></section><section class="panel"><h2>Services</h2><div id="stable-items">${itemInputs()}</div><button onclick="draft.items.push({name:'',description:'',qty:1,rate:0});render()">+ Add service</button></section><section class="panel"><h2>Terms</h2><textarea id="doc-terms">${esc(d.terms)}</textarea></section>${d.type==='Invoice'?`<section class="panel"><h2>Payments</h2><div id="payment-list">${(d.payments||[]).map(p=>`<p>${esc(p.date)} · ${stableMoney(d,p.amount)} · ${esc(p.reference||'Payment')}</p>`).join('')||'<p>No payments recorded.</p>'}</div><div class="grid three">${input('Date','payment-date',today(),'date')}${input('Amount','payment-amount','','number')}${input('Reference','payment-reference','')}</div><button onclick="addPayment()">Record payment</button></section>`:''}</div><aside class="stack"><section class="panel summary"><h2>Total</h2><div class="grid">${input('Discount %','doc-discount',d.discount,'number')}${input('Tax %','doc-tax',d.tax,'number')}</div><div id="total"></div></section></aside></div>`}
function input(label,id,value,type='text'){return `<label>${label}<input id="${id}" type="${type}" value="${esc(value)}"></label>`}
function itemInputs(){return draft.items.map((i,n)=>`<div class="lineitem"><div><label>Service<input value="${esc(i.name)}" oninput="draft.items[${n}].name=this.value"></label><label>Description<textarea oninput="draft.items[${n}].description=this.value">${esc(i.description||'')}</textarea></label></div><label>Qty<input type="number" value="${num(i.qty)||1}" oninput="draft.items[${n}].qty=num(this.value);updateTotal()"></label><label>Rate<input type="number" value="${num(i.rate)}" oninput="draft.items[${n}].rate=num(this.value);updateTotal()"></label><button onclick="draft.items.splice(${n},1);render()">×</button></div>`).join('')}
function updateTotal(){if(!draft)return;const el=document.getElementById('total'),t=totals(draft);if(el)el.innerHTML=`<div class="totalrow"><span>Subtotal</span><b>${stableMoney(draft,t.subtotal)}</b></div><div class="totalrow"><span>Tax</span><b>${stableMoney(draft,t.tax)}</b></div><div class="totalrow big"><span>Total</span><b>${stableMoney(draft,t.total)}</b></div>${draft.type==='Invoice'?`<div class="totalrow"><span>Paid</span><b>${stableMoney(draft,t.paid)}</b></div><div class="totalrow"><span>Balance</span><b>${stableMoney(draft,t.balance)}</b></div>`:''}`}
function readDraft(){draft.number=document.getElementById('doc-number').value.trim();draft.date=document.getElementById('doc-date').value;draft.due=document.getElementById('doc-due').value;draft.project=document.getElementById('doc-project').value;draft.currency=document.getElementById('doc-currency').value;draft.status=document.getElementById('doc-status').value;draft.discount=num(document.getElementById('doc-discount').value);draft.tax=num(document.getElementById('doc-tax').value);draft.terms=document.getElementById('doc-terms').value;for(const key of ['name','contact','email','phone','address'])draft.client[key]=document.getElementById('client-'+key).value;draft.updated=new Date().toISOString()}
function saveDoc(){readDraft();if(!draft.number||!draft.client.name||!draft.date||!draft.due||!draft.items.length||draft.items.some(i=>!i.name||num(i.qty)<=0||num(i.rate)<0)){toast('Complete the document, client, and service details.');return false}const index=db.documents.findIndex(d=>d.id===draft.id);if(index<0)db.documents.push(structuredClone(draft));else db.documents[index]=structuredClone(draft);const clientIndex=db.clients.findIndex(c=>c.id===draft.client.id||c.name.toLowerCase()===draft.client.name.toLowerCase());const client={...(clientIndex>=0?db.clients[clientIndex]:{}),...draft.client,id:clientIndex>=0?db.clients[clientIndex].id:uid()};if(clientIndex<0)db.clients.push(client);else db.clients[clientIndex]=client;db.documents.find(d=>d.id===draft.id).client.id=client.id;if(!stablePersist())return false;draft=null;render();toast('Document saved.');return true}
function cancelEdit(){draft=null;render()}
function addPayment(){const amount=num(document.getElementById('payment-amount').value),date=document.getElementById('payment-date').value;if(amount<=0||!date){toast('Enter a payment date and amount.');return}draft.payments.push({id:uid(),date,amount,reference:document.getElementById('payment-reference').value});render()}
function documentHTML(d){const t=totals(d);return `<article class="document"><div class="dochead"><div><img class="doclogo" src="./assets/pdf-quotation-logo-clean.png"><small>${esc((d.business||db.settings).tagline)}<br>${esc((d.business||db.settings).address)}</small></div><div><h2>${esc(typeLabel(d.type).toUpperCase())}</h2><small>${esc(d.number)}</small></div></div><div class="reference-rule"></div><div class="docmeta"><div><h3>${d.type==='Quotation'?'PREPARED FOR':'BILL TO'}</h3><b>${esc(d.client.name)}</b><br>${esc(d.client.contact)}<br>${esc(d.client.address)}<br>${esc(d.client.phone)}</div><div><h3>DETAILS</h3>Date: ${esc(d.date)}<br>Due: ${esc(d.due)}<br>Project: ${esc(d.project)}</div></div><h3>SERVICES</h3><table><thead><tr><th>#</th><th>Service / description</th><th>Qty</th><th>Rate</th><th>Amount</th></tr></thead><tbody>${d.items.map((i,n)=>`<tr><td>${n+1}</td><td><b>${esc(i.name)}</b><small>${esc(i.description)}</small></td><td>${num(i.qty)}</td><td>${stableMoney(d,i.rate)}</td><td>${stableMoney(d,num(i.qty)*num(i.rate))}</td></tr>`).join('')}</tbody></table><div class="doctotals"><div class="totalrow"><span>Subtotal</span><span>${stableMoney(d,t.subtotal)}</span></div><div class="totalrow"><span>GST / tax (${num(d.tax)}%)</span><span>${stableMoney(d,t.tax)}</span></div><div class="totalrow big"><span>TOTAL</span><span>${stableMoney(d,t.total)}</span></div></div><div class="docnotes"><h3>TERMS & CONDITIONS</h3>${esc(d.terms)}</div></article>`}
function showPreview(id){previewDoc=structuredClone(db.documents.find(d=>d.id===id));if(!previewDoc)return;const dialog=document.getElementById('preview');dialog.innerHTML=`<div class="modalbar"><div><strong>${esc(typeLabel(previewDoc.type))}</strong><small>${esc(previewDoc.number)}</small></div><div class="actions"><button onclick="editDocument('${previewDoc.id}')">Edit</button><button onclick="downloadDocumentPdf('${previewDoc.id}')" class="primary">Download PDF</button><button onclick="document.getElementById('preview').close()">Close</button></div></div><div id="previewBody">${documentHTML(previewDoc)}</div>`;dialog.showModal()}
function previewDraft(){readDraft();const dialog=document.getElementById('preview');previewDoc=structuredClone(draft);dialog.innerHTML=`<div class="modalbar"><strong>Preview</strong><div class="actions"><button onclick="document.getElementById('preview').close()">Close</button></div></div><div id="previewBody">${documentHTML(previewDoc)}</div>`;dialog.showModal()}
async function downloadDocumentPdf(id){const record=db.documents.find(d=>d.id===id)||previewDoc;if(!record)return;try{const file=await createDocumentPdf(record);const url=URL.createObjectURL(file),a=document.createElement('a');a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch{toast('Could not create the PDF.')}}
function clients(){return page('Clients',`<button class="primary" onclick="newDoc('Quotation')">+ Quotation</button>`,'Clients are saved when you save a document.')+`<section class="panel">${db.clients.length?`<div class="tablewrap"><table><thead><tr><th>Client</th><th>Contact</th><th>Email</th><th>Phone</th></tr></thead><tbody>${db.clients.map(c=>`<tr><td><b>${esc(c.name)}</b></td><td>${esc(c.contact)}</td><td>${esc(c.email)}</td><td>${esc(c.phone)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty"><h2>No clients yet.</h2></div>'}</section>`}
function projects(){return page('Projects','','Projects are tracked from your documents.')+`<section class="panel"><p class="sub">Create a quotation or invoice, then use its project name to track work here.</p></section>`}
function followups(){return page('Follow-ups','','Follow-up tracking is available from saved client records.')+`<section class="panel"><p class="sub">No follow-ups are scheduled.</p></section>`}
function services(){return page('Services','','Reference services for new work.')+`<section class="panel"><div class="catalog">${db.services.map(s=>`<article class="service"><h2>${esc(s.name)}</h2><p>${esc(s.description)}</p><b>INR ${num(s.rate).toLocaleString('en-IN')}</b></article>`).join('')}</div></section>`}
function settings(){return page('Settings',`<button class="primary" onclick="saveSettings()">Save settings</button>`,'Business and payment details used for new documents.')+`<section class="panel"><div class="grid">${['name','tagline','address','email','phone','account','bank','accountNo','ifsc','upi'].map(k=>input(k,'setting-'+k,db.settings[k]||'')).join('')}<label>Default tax %<input id="setting-tax" type="number" value="${num(db.settings.tax)}"></label></div></section>`}
function saveSettings(){for(const k of ['name','tagline','address','email','phone','account','bank','accountNo','ifsc','upi'])db.settings[k]=document.getElementById('setting-'+k).value;db.settings.tax=num(document.getElementById('setting-tax').value);if(stablePersist())toast('Settings saved.')}
render();
