(function(root){
  'use strict';
  const PAGE={w:210,h:297,margin:16,right:194,width:178};
  const COLOR={ink:[22,30,39],muted:[91,101,112],gold:[190,157,78],line:[211,212,207],navy:[27,42,30],wash:[248,247,242]};
  const FORMAT={
    Quotation:{title:'QUOTATION',eyebrow:'PROPOSAL',client:'PREPARED FOR',details:'QUOTATION DETAILS',section:'SERVICES QUOTED',footer:'Thank you for considering Eric’s Designs.',payment:false},
    Proforma:{title:'PROFORMA INVOICE',eyebrow:'ADVANCE PAYMENT REQUEST',client:'BILL TO',details:'PROFORMA DETAILS',section:'SERVICES TO BE PROVIDED',footer:'Thank you for considering Eric’s Designs.',payment:true},
    Invoice:{title:'FINAL INVOICE',eyebrow:'TAX INVOICE',client:'BILL TO',details:'INVOICE DETAILS',section:'SERVICES PROVIDED',footer:'Thank you for choosing Eric’s Designs.',payment:true},
    Receipt:{title:'PAYMENT RECEIPT',eyebrow:'PAYMENT CONFIRMATION',client:'RECEIVED FROM',details:'RECEIPT DETAILS',section:'PAYMENTS RECEIVED',footer:'Thank you for your payment.',payment:false}
  };
  const DEFAULT_PAYMENT={account:'ERIC RODGERS',accountNo:'50100486607332',ifsc:'HDFC0000682',bank:'HDFC Bank, ALAPPUZHA',upi:'ericrodgers555@oksbi'};
  const typeOf=value=>value==='Final Invoice'?'Invoice':FORMAT[value]?value:'Quotation';
  const clean=value=>String(value??'').replace(/₹/g,'INR ').replace(/[\u2013\u2014]/g,'-');
  const calc=doc=>{const subtotal=(doc.items||[]).reduce((sum,item)=>sum+Number(item.qty||1)*Number(item.rate||0),0),discount=subtotal*Number(doc.discount||0)/100,base=subtotal-discount,tax=base*Number(doc.tax||0)/100,total=base+tax,paid=(doc.payments||[]).reduce((sum,payment)=>sum+Number(payment.amount||0),0);return {subtotal,discount,tax,total,paid,balance:Math.max(0,total-paid)}};
  const amount=(doc,value)=>`${doc.currency==='AED'?'AED':'INR'} ${Number(value||0).toLocaleString(doc.currency==='AED'?'en-AE':'en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
  const asset=async path=>{try{const response=await fetch(path,{cache:'no-store'});if(!response.ok)return null;const blob=await response.blob();return await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(blob)})}catch{return null}};
  function buildPdf(doc,inputType,jsPDF,logo,qr){
    const type=typeOf(inputType||doc.type),template=(root.getPdfTemplateDesign?.(type)||{}),format={...FORMAT[type],...Object.fromEntries(['eyebrow','title','footer'].filter(key=>template[key]).map(key=>[key,template[key]]))},accent=String(template.accent||'#be9d4e').replace('#',''),accentRgb=accent.length===6?[parseInt(accent.slice(0,2),16),parseInt(accent.slice(2,4),16),parseInt(accent.slice(4,6),16)]:COLOR.gold,logoWidth=Math.max(35,Math.min(95,Number(template.logoWidth)||68)),pdf=new jsPDF({unit:'mm',format:'a4',compress:true}),business=doc.business||{},totals=calc(doc),payment={...DEFAULT_PAYMENT,...Object.fromEntries(Object.entries(business).filter(([key])=>['account','accountNo','ifsc','bank','upi'].includes(key)))};
    let y=17;
    const font=(size=9,style='normal',colour=COLOR.ink)=>{pdf.setFont('helvetica',style);pdf.setFontSize(size);pdf.setTextColor(...colour)};
    const write=(value,x,yy,size=9,style='normal',align='left',colour=COLOR.ink)=>{font(size,style,colour);pdf.text(Array.isArray(value)?value.map(clean):clean(value),x,yy,{align})};
    const wrap=(value,width)=>pdf.splitTextToSize(clean(value||'-'),width);
    const rule=(yy,colour=COLOR.line,width=.25)=>{pdf.setDrawColor(...colour);pdf.setLineWidth(width);pdf.line(PAGE.margin,yy,PAGE.right,yy)};
    const pageFooter=()=>{rule(286,accentRgb,.35);write([business.name||"Eric's Designs",business.address].filter(Boolean).join(' - '),105,291,6.7,'normal','center',COLOR.muted)};
    const brand=continued=>{if(logo)try{pdf.addImage(logo,'PNG',PAGE.margin,15,logoWidth,logoWidth*.2)}catch{};write(format.eyebrow,PAGE.right,17,6.8,'bold','right',accentRgb);write(format.title,PAGE.right,25,16,'bold','right');write(doc.number||'ED-0000',PAGE.right,31,8,'normal','right',COLOR.muted);y=40;rule(y,accentRgb,.4);y+=8;if(continued){write(format.section+' - CONTINUED',PAGE.margin,y,8,'bold','left',accentRgb);y+=7;return;}write(format.client,PAGE.margin,y,8,'bold','left',accentRgb);write(format.details,PAGE.right,y,8,'bold','right',accentRgb);const client=doc.client||{};const left=[...wrap(client.name||'-',84),...[client.contact,client.address,client.email,client.phone].filter(Boolean).flatMap(value=>wrap(value,84))].slice(0,8);const meta=type==='Receipt'?[['Receipt date',doc.date],['Invoice',doc.number],['Currency',doc.currency||'INR']]:type==='Quotation'?[['Issue date',doc.date],['Valid until',doc.due],['Currency',doc.currency||'INR']]:[['Issue date',doc.date],['Due date',doc.due],['Project',doc.project||'-'],['Currency',doc.currency||'INR']];const right=meta.flatMap(([label,value])=>wrap(label+': '+(value||'-'),68));const start=y+7;write(left[0]||'-',PAGE.margin,start,9.5,'bold');if(left.length>1)write(left.slice(1),PAGE.margin,start+4.5,8.1,'normal');write(right,PAGE.right,start,8.1,'normal','right');y=Math.max(start+left.length*4.3,start+right.length*4.3)+6;};
    const columns=type==='Receipt'?[PAGE.margin,52,159,PAGE.right]:type==='Quotation'?[PAGE.margin,29,88,160,PAGE.right]:[PAGE.margin,28,116,139,166,PAGE.right];
    const heads=type==='Receipt'?['DATE','REFERENCE / METHOD','AMOUNT']:type==='Quotation'?['#','SERVICE','DESCRIPTION','PRICE']:['#','SERVICE / DESCRIPTION','QTY','RATE','AMOUNT'];
    const tableHead=continued=>{if(continued)brand(true);else{write(format.section,PAGE.margin,y,8,'bold','left',accentRgb);y+=6}pdf.setFillColor(...COLOR.navy);pdf.roundedRect(PAGE.margin,y,PAGE.width,10,1,1,'F');heads.forEach((head,index)=>write(head,index<2?columns[index]+2:columns[index+1]-2,y+6.3,6.9,'bold',index<2?'left':'right',[255,255,255]));y+=14;};
    const rows=type==='Receipt'?(doc.payments||[]).map(item=>[item.date||'-',item.reference||'Payment received',amount(doc,item.amount)]):(doc.items||[]).map((item,index)=>type==='Quotation'?[String(index+1),item.name||'-',item.description||'-',item.rateText||amount(doc,item.rate)]:[String(index+1),[item.name,item.description].filter(Boolean).join('\n')||'-',String(item.qty||1),item.rateText||amount(doc,item.rate),amount(doc,Number(item.qty||1)*Number(item.rate||0))]);
    brand(false);if(type==='Quotation'&&doc.project){rule(y);y+=6;write('PROJECT SUMMARY',PAGE.margin,y,7.7,'bold','left',accentRgb);const summary=wrap(doc.project,PAGE.width-8).slice(0,3);write(summary,PAGE.margin,y+5,7.5,'normal');y+=summary.length*3.8+10;}tableHead(false);if(!rows.length)rows.push(type==='Receipt'?['-','No payment recorded','-']:['-','No items added','','','']);
    for(const row of rows){const cells=row.map((value,index)=>wrap(value,columns[index+1]-columns[index]-4));const height=Math.max(11,...cells.map(lines=>lines.length*3.9+5));if(y+height>228){pdf.addPage();tableHead(true)}cells.forEach((lines,index)=>write(lines,index<2?columns[index]+2:columns[index+1]-2,y+5.1,index===1?7.8:7.4,index===1?'bold':'normal',index<2?'left':'right',index===2&&type==='Quotation'?COLOR.muted:COLOR.ink));rule(y+height);y+=height+2;}
    if(type==='Quotation'){write('Tailored services are provided on request',PAGE.right,y+4,7.8,'italic','right',COLOR.muted);y+=12;}else{const totalsRows=type==='Receipt'?[['PAYMENT RECEIVED',totals.paid,true]]:[['Subtotal',totals.subtotal],...(totals.discount?[['Discount',-totals.discount]]:[]),['GST / tax ('+Number(doc.tax||0)+'%)',totals.tax],['TOTAL DUE',totals.total,true],...(type==='Invoice'?[['Paid',totals.paid],['BALANCE DUE',totals.balance,true]]:[])];const x=PAGE.right-57;rule(y+1);y+=7;totalsRows.forEach(([label,value,strong])=>{if(strong)rule(y-3);write(label,x,y,8.1,strong?'bold':'normal');write(amount(doc,value),PAGE.right,y,8.2,strong?'bold':'normal','right');y+=strong?7:5.3});y+=5;}
    const notes=String(doc.terms||'').split(/\n/).map(item=>item.trim()).filter(Boolean);
    const noteLines=notes.flatMap(note=>wrap(note.replace(/^[•*-]\s*/,''),type==='Quotation'?PAGE.width-8:104));
    if(format.payment){
      const compactNotes=noteLines.slice(0,3),paymentRows=[['Account holder',payment.account],['Account number',payment.accountNo],['IFSC',payment.ifsc],['Bank',payment.bank],['UPI',payment.upi]];
      const blockH=Math.max(32,12+compactNotes.length*3+paymentRows.length*3.1);
      if(y+blockH>270){pdf.addPage();brand(true);}
      rule(y,accentRgb,.4);y+=6;write('TERMS & CONDITIONS',PAGE.margin,y,7.5,'bold','left',accentRgb);write('PAYMENT DETAILS',126,y,7.5,'bold','left',accentRgb);write('SCAN TO PAY',PAGE.right,y,6.5,'bold','right',accentRgb);y+=5;rule(y);let noteY=y+5;compactNotes.forEach((line,index)=>write((index===0?'- ':'')+line,PAGE.margin+2,noteY+index*3.3,6.7));const payY=noteY;paymentRows.forEach(([label,value],index)=>write(label+': '+value,126,payY+index*3.35,6.6));if(qr&&template.showQr!==false)try{pdf.addImage(qr,'JPEG',PAGE.right-14,payY-2,14,18)}catch{}y=Math.max(noteY+compactNotes.length*3.3,payY+paymentRows.length*3.35,payY+18)+4;
    }else if(notes.length){
      if(y+26>250){pdf.addPage();brand(true);}rule(y,accentRgb,.4);y+=7;write(type==='Receipt'?'RECEIPT NOTES':'TERMS & CONDITIONS',PAGE.margin,y,8,'bold','left',accentRgb);y+=5;rule(y);y+=6;for(const note of notes){const lines=wrap(note.replace(/^[•*-]\s*/,''),PAGE.width-8);if(y+lines.length*3.8>258){pdf.addPage();brand(true);}write('- '+lines[0],PAGE.margin+3,y,7.4);if(lines.length>1)write(lines.slice(1),PAGE.margin+7,y+3.8,7.4);y+=Math.max(5,lines.length*3.8)}
    }
    const footerY=y > 254 ? 278 : Math.max(267,Math.min(278,y+10));write(format.footer,PAGE.margin,footerY-9,8.1,'italic');write(business.name||"Eric's Designs",PAGE.margin,footerY,7.5,'bold');write([business.phone,business.email].filter(Boolean).join(' | '),PAGE.margin,footerY+4.4,6.9,'normal','left',COLOR.muted);pageFooter();return pdf;
  }
  async function file(doc,type){const jsPDF=root.jspdf?.jsPDF||(await root.loadInvoicePdfLibrary()),[logo,qr]=await Promise.all([asset('./assets/pdf-quotation-logo-clean.png'),asset('./assets/eric-rodgers-google-pay-qr.jpeg')]),pdf=buildPdf(doc,type,jsPDF,logo,qr),stamp=new Date().toISOString().replace(/[-:.TZ]/g,'').slice(0,14);return new File([pdf.output('blob')],`${doc.number||'document'}-${stamp}.pdf`,{type:'application/pdf'})}
  if(typeof module!=='undefined'&&module.exports)module.exports={buildPdf,FORMAT};
  if(root&&root.document){root.createDocumentPdf=doc=>file(doc,typeOf(doc?.type));root.createInvoicePdf=doc=>file(doc,'Invoice');root.createQuotationPdf=doc=>file(doc,'Quotation');root.createProformaPdf=doc=>file(doc,'Proforma');root.createPaymentReceiptPdf=invoice=>file({...invoice,type:'Receipt',items:[],payments:invoice.payments||[],number:(invoice.number||'ED-0000')+' RECEIPT'},'Receipt')}
})(typeof window!=='undefined'?window:globalThis);
