(function(root){
  'use strict';
  const A4={width:210,height:297,margin:16};
  const COLORS={ink:[22,30,39],muted:[83,96,110],gold:[190,157,78],table:[30,43,27],line:[207,208,202]};
  const profile={
    Quotation:{title:'QUOTATION',client:'PREPARED FOR',details:'DETAILS',section:'SERVICES QUOTED',footer:'Thank you for considering Eric’s Designs.'},
    Invoice:{title:'INVOICE',client:'BILL TO',details:'DETAILS',section:'SERVICES PROVIDED',footer:'Thank you for choosing Eric’s Designs.'},
    Proforma:{title:'PROFORMA INVOICE',client:'BILL TO',details:'PROFORMA DETAILS',section:'SERVICES TO BE PROVIDED',footer:'Thank you for considering Eric’s Designs.'},
    Receipt:{title:'PAYMENT RECEIPT',client:'RECEIVED FROM',details:'PAYMENT SUMMARY',section:'PAYMENTS RECORDED',footer:'Thank you for your payment.'}
  };
  const clean=value=>String(value??'').replace(/₹/g,'INR ').replace(/[\u2013\u2014]/g,'-');
  const escapeHtml=value=>String(value??'').replace(/[&<>\"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[char]));
  const money=(doc,value)=>`${doc.currency==='AED'?'AED':'INR'} ${Number(value||0).toLocaleString(doc.currency==='AED'?'en-AE':'en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
  const calculate=doc=>{const subtotal=(doc.items||[]).reduce((sum,item)=>sum+Number(item.qty||1)*Number(item.rate||0),0),discount=subtotal*Number(doc.discount||0)/100,base=subtotal-discount,tax=base*Number(doc.tax||0)/100,total=base+tax,paid=(doc.payments||[]).reduce((sum,payment)=>sum+Number(payment.amount||0),0);return {subtotal,discount,tax,total,paid,balance:Math.max(0,total-paid)}};
  function buildPdf(doc,type,jsPDF,logoData){
    const pdf=new jsPDF({unit:'mm',format:'a4',compress:true}),p=profile[type]||profile.Quotation,margin=A4.margin,right=A4.width-margin,width=right-margin,totals=calculate(doc),business=doc.business||{},quotation=type==='Quotation',receipt=type==='Receipt',invoice=type==='Invoice';
    let y=18;
    const text=(value,x,yy,size=9,style='normal',align='left',color=COLORS.ink)=>{pdf.setFont('helvetica',style);pdf.setFontSize(size);pdf.setTextColor(...color);pdf.text(Array.isArray(value)?value.map(clean):clean(value),x,yy,{align});};
    const line=(yy,color=COLORS.line,thickness=.25)=>{pdf.setDrawColor(...color);pdf.setLineWidth(thickness);pdf.line(margin,yy,right,yy)};
    const rule=yy=>line(yy,COLORS.gold,.42);
    const addLogo=()=>{if(logoData){try{pdf.addImage(logoData,'PNG',margin,15,64,20)}catch{}}};
    const top=continued=>{addLogo();text(p.title,right,24,17,'bold','right');text(doc.number||'ED-0000',right,31,8,'normal','right',COLORS.muted);y=46;rule(y);y+=11;text(continued?p.section+' (CONTINUED)':p.client,margin,y,8.5,'bold','left',COLORS.gold);if(!continued){text(p.details,right,y,8.5,'bold','right',COLORS.gold);const client=doc.client||{};text(client.name||'-',margin,y+11,10,'bold');[client.contact,client.address,client.email,client.phone].filter(Boolean).slice(0,3).forEach((item,index)=>text(item,margin,y+17+index*4.8,8.2));const details=receipt?[['Receipt date',doc.date],['Invoice',doc.number],['Currency',doc.currency||'INR']]:quotation?[['Date',doc.date],['Valid until',doc.due],['Project',doc.project||'-'],['Currency',doc.currency||'INR']]:[['Invoice no.',doc.number],['Date of issue',doc.date],['Due date',doc.due],['Project',doc.project||'-']];details.forEach(([label,value],index)=>text(`${label}: ${value||'-'}`,right,y+11+index*4.8,8.2,'normal','right'));y+=37}else y+=7;};
    const columnSet=receipt?[margin,margin+38,right-35,right]:quotation?[margin,margin+14,margin+58,right-34,right]:[margin,margin+11,right-80,right-56,right-28,right];
    const headers=receipt?['DATE','REFERENCE / METHOD','AMOUNT']:quotation?['NO.','SERVICE','DESCRIPTION','PRICE ('+(doc.currency||'INR')+')']:['#','SERVICE DESCRIPTION','QTY','RATE ('+(doc.currency||'INR')+')','AMOUNT ('+(doc.currency||'INR')+')'];
    const tableHead=continued=>{if(continued)top(true);else {text(p.section,margin,y,8.5,'bold','left',COLORS.gold);y+=7}pdf.setFillColor(...COLORS.table);pdf.rect(margin,y,width,11,'F');headers.forEach((header,index)=>text(header,index<=1?columnSet[index]+2:columnSet[index+1]-2,y+6.7,7.1,'bold',index<=1?'left':'right',[255,255,255]));y+=15;};
    const rows=receipt?(doc.payments||[]).map(payment=>[payment.date||'-',payment.reference||'Payment received',money(doc,payment.amount)]):(doc.items||[]).map((item,index)=>quotation?[String(index+1).padStart(2,'0'),item.name||'-',item.description||'-',item.rateText||money(doc,item.rate)]:[String(index+1),[item.name,item.description].filter(Boolean).join(' - ')||'-',String(item.qty||1),item.rateText||money(doc,item.rate),money(doc,Number(item.qty||1)*Number(item.rate||0))]);
    top(false);tableHead(false);
    for(const row of rows){const lines=row.map((value,index)=>pdf.splitTextToSize(clean(value),columnSet[index+1]-columnSet[index]-4));const height=Math.max(12,...lines.map(cell=>cell.length*3.8+5));if(y+height>244){pdf.addPage();tableHead(true)}lines.forEach((cell,index)=>text(cell,index<=1?columnSet[index]+2:columnSet[index+1]-2,y+5.2,index===1?7.9:7.4,index===1?'bold':'normal',index<=1?'left':'right',index===2&&quotation?COLORS.muted:COLORS.ink));line(y+height);y+=height+2;}
    if(quotation){text('Tailored services are provided on request',right,y+3,8.2,'italic','right');y+=13}else{const summary=receipt?[['PAYMENT RECEIVED',totals.paid]]:[['Subtotal',totals.subtotal],['GST ('+Number(doc.tax||0)+'%)',totals.tax],['TOTAL DUE',totals.total],...(invoice?[['Paid',totals.paid],['BALANCE DUE',totals.balance]]:[])];summary.forEach(([label,value])=>{const strong=label==='TOTAL DUE'||label==='BALANCE DUE';text(label,right-52,y,8.2,strong?'bold':'normal');text(money(doc,value),right,y,8.3,strong?'bold':'normal','right');y+=strong?6.5:5.2});y+=5;}
    const noteTitle=invoice?'PAYMENT DETAILS':receipt?'RECEIPT NOTES':'TERMS & CONDITIONS';const details=invoice?[business.account&&'Account holder: '+business.account,business.accountNo&&'Account number: '+business.accountNo,business.ifsc&&'IFSC: '+business.ifsc,business.bank&&'Bank and branch: '+business.bank,business.upi&&'UPI ID: '+business.upi].filter(Boolean):[doc.terms||''];if(y+28>252){pdf.addPage();y=20}rule(y);y+=7;text(noteTitle,margin,y,8.5,'bold','left',COLORS.gold);y+=5;line(y);y+=6;for(const note of details.join('\n').split(/\n/).filter(Boolean)){const lines=pdf.splitTextToSize(clean(note).replace(/^[•*-]\s*/,''),width-7);if(y+lines.length*4.1>258){pdf.addPage();y=20;rule(y);y+=8}text('- '+lines[0],margin+3,y,7.7);if(lines.length>1)text(lines.slice(1),margin+7,y+4.1,7.7);y+=Math.max(5,lines.length*4.1)}
    const footerY=Math.max(267,Math.min(280,y+14));text(p.footer,margin,footerY-10,8.3,'italic');text((business.name||"Eric's Designs"),margin,footerY,7.6,'bold');text([business.phone,business.email].filter(Boolean).join(' | '),margin,footerY+4.5,7.1,'normal','left',COLORS.muted);rule(286);text([business.name,business.address].filter(Boolean).join(' - '),105,291,6.7,'normal','center',COLORS.muted);return pdf;
  }
  async function browserLogo(){try{const response=await fetch('./assets/pdf-quotation-logo-clean.png',{cache:'no-store'});if(!response.ok)return null;const blob=await response.blob();return await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(blob)});}catch{return null}}
  async function fileForDocument(doc,type){const jsPDF=await root.loadInvoicePdfLibrary(),logo=await browserLogo(),pdf=buildPdf(doc,type,jsPDF,logo),stamp=new Date().toISOString().replace(/[-:.TZ]/g,'').slice(0,14);return new File([pdf.output('blob')],`${doc.number||'document'}-${stamp}.pdf`,{type:'application/pdf'})}
  function preview(doc){const type=doc.type||'Quotation',quotation=type==='Quotation',receipt=type==='Receipt',invoice=type==='Invoice',p=profile[type]||profile.Quotation,t=calculate(doc),headers=receipt?['DATE','REFERENCE / METHOD','AMOUNT']:quotation?['NO.','SERVICE','DESCRIPTION','PRICE']:['#','SERVICE DESCRIPTION','QTY','RATE','AMOUNT'],rows=receipt?(doc.payments||[]).map(x=>[x.date||'-',x.reference||'Payment received',money(doc,x.amount)]):(doc.items||[]).map((item,index)=>quotation?[String(index+1),item.name||'-',item.description||'-',item.rateText||money(doc,item.rate)]:[String(index+1),[item.name,item.description].filter(Boolean).join(' - ')||'-',String(item.qty||1),item.rateText||money(doc,item.rate),money(doc,Number(item.qty||1)*Number(item.rate||0))]);return `<article class="document reference-document fixed-pdf-preview"><div class="dochead"><div><img class="doclogo" src="./assets/pdf-quotation-logo-clean.png" alt="Eric's Designs"><small>${escapeHtml((doc.business||{}).tagline||'Software Development & Digital Marketing Agency')}<br>${escapeHtml((doc.business||{}).address||'Mumbai, Maharashtra, India')}</small></div><div><h2>${p.title}</h2><small>${escapeHtml(doc.number||'ED-0000')}</small></div></div><div class="reference-rule"></div><div class="docmeta"><div><h3>${p.client}</h3><b>${escapeHtml(doc.client?.name||'-')}</b><br>${[doc.client?.contact,doc.client?.address,doc.client?.email,doc.client?.phone].filter(Boolean).map(escapeHtml).join('<br>')}</div><div><h3>${p.details}</h3>Invoice no.: ${escapeHtml(doc.number||'-')}<br>Date of issue: ${escapeHtml(doc.date||'-')}<br>Due date: ${escapeHtml(doc.due||'-')}<br>Project: ${escapeHtml(doc.project||'-')}</div></div><h3>${p.section}</h3><table class="reference-table columns-${headers.length}"><thead><tr>${headers.map(escapeHtml).map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(escapeHtml).map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table>${quotation?'<p class="reference-tailored">Tailored services are provided on request</p>':`<div class="doctotals"><div class="totalrow"><span>Subtotal</span><span>${money(doc,t.subtotal)}</span></div><div class="totalrow"><span>GST (${Number(doc.tax||0)}%)</span><span>${money(doc,t.tax)}</span></div><div class="totalrow big"><span>${receipt?'PAYMENT RECEIVED':'TOTAL DUE'}</span><span>${money(doc,receipt?t.paid:t.total)}</span></div></div>`}<div class="docnotes"><h3>${invoice?'PAYMENT DETAILS':receipt?'RECEIPT NOTES':'TERMS & CONDITIONS'}</h3>${escapeHtml(invoice?'Account details are shown in the downloaded invoice.':doc.terms||'')}</div></article>`}
  if(typeof module!=='undefined'&&module.exports)module.exports={buildPdf,profile,preview};
  if(root&&root.document){root.createDocumentPdf=doc=>fileForDocument(doc,doc?.type||'Quotation');root.createInvoicePdf=doc=>fileForDocument(doc,'Invoice');root.createQuotationPdf=doc=>fileForDocument(doc,'Quotation');root.createProformaPdf=doc=>fileForDocument(doc,'Proforma');root.createPaymentReceiptPdf=invoice=>fileForDocument({...invoice,type:'Receipt',items:[],payments:invoice.payments||[],number:(invoice.number||'ED-0000')+' RECEIPT'},'Receipt');}
})(typeof window!=='undefined'?window:globalThis);
