(function(root){
'use strict';
const FORMAT={Quotation:{title:'QUOTATION',payment:false},Invoice:{title:'INVOICE',payment:true},Proforma:{title:'PROFORMA INVOICE',payment:true},Receipt:{title:'PAYMENT RECEIPT',payment:false}};
const typeOf=t=>t==='Final Invoice'?'Invoice':FORMAT[t]?t:'Quotation';
const clean=v=>String(v??'').replace(/₹/g,'INR ').replace(/[\u2013\u2014]/g,'-').replace(/[\u2018\u2019]/g,"'");
function buildPdf(doc,inputType,jsPDF,logo,qr){
 const type=typeOf(inputType||doc.type),quote=type==='Quotation',receipt=type==='Receipt',voucher=receipt&&doc.receiptKind==='Payment voucher',f=FORMAT[type],pdf=new jsPDF({unit:'mm',format:'a4',compress:true});
 const b=doc.business||{},client=doc.client||{},m=18,r=192,w=r-m,gold=[153,115,51],ink=[32,29,26],muted=[105,99,87];let y=20;
 const text=(v,x,yy,size=9,style='normal',align='left',color=ink)=>{pdf.setFont('times',style);pdf.setFontSize(size);pdf.setTextColor(...color);pdf.text(Array.isArray(v)?v.map(clean):clean(v),x,yy,{align,lineHeightFactor:1.15});};
 const wrap=(v,width,size=9,style='normal')=>{pdf.setFont('times',style);pdf.setFontSize(size);return pdf.splitTextToSize(clean(v),width)};
 const rule=yy=>{pdf.setDrawColor(198,185,165);pdf.setLineWidth(.2);pdf.line(m,yy,r,yy)};
 const money=v=>(doc.currency||'INR')+' '+Number(v||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});
 const newPage=()=>{pdf.addPage();text(f.title+' / '+(doc.number||''),m,16,10,'bold');rule(20);y=27;};
 const ensure=h=>{if(y+h>273)newPage()};
 const paragraph=(value,width=w,size=9,style='normal',x=m,color=ink)=>{for(const line of wrap(value,width,size,style)){ensure(5);text(line,x,y,size,style,'left',color);y+=size*.405;}y+=.7;};
 const heading=label=>{ensure(11);text(label,m,y,8.5,'bold','left',gold);y+=2.5;rule(y);y+=4.5;};
 if(quote){if(logo)pdf.addImage(logo,'PNG',r-19,12,10,21);text((b.name||"Eric's Designs").toUpperCase(),m,22,16,'bold');text(b.tagline||'Creative & Digital Marketing Agency',m,28,9,'italic','left',muted);text(f.title,m,39,22,'bold','left',gold);rule(45);y=51;}
 else{if(logo)pdf.addImage(logo,'PNG',m,12,13,27);text((b.name||"Eric's Designs").toUpperCase(),m+24,24,16,'bold','left',gold);text(b.tagline||'Marketing & Creative Design Studio',m+24,29,8.5,'italic','left',muted);text(receipt&&voucher?'PAYMENT VOUCHER':f.title,r,26,type==='Proforma'?15:18,'bold','right');rule(43);y=49;}
 const left=quote?[['DATE',doc.date],['VALID UNTIL',doc.due]]:receipt?[[voucher?'PAYEE':'CLIENT',client.name]]:[['CLIENT',client.name],['ADDRESS',client.address],['EMAIL',client.email],['PHONE',client.phone],['CONTACT',client.contact],['GSTIN',client.gstin]];
 text(quote?'QUOTATION DETAILS':receipt?(voucher?'PAID TO':'RECEIVED FROM'):'BILL TO',m,y,8,'bold','left',gold);text('DETAILS',r,y,8,'bold','right',gold);y+=5;const start=y;
 for(const [key,value] of left){if(value)paragraph(key+'  '+value,90,9,'normal',m)}
 if(quote){for(const value of [client.name,client.contact,client.address,client.email,client.phone,client.gstin].filter(Boolean))paragraph(value,90,9);}
 const leftEnd=y;y=start;for(const value of [doc.number,doc.status==='Cancelled'?'CANCELLED':null,!quote?'Date of issue: '+(doc.date||'-'):null,!quote?'Due date: '+(doc.due||'-'):null,'Currency: '+(doc.currency||'INR'),b.gstin?'GSTIN: '+b.gstin:null].filter(Boolean)){const lines=wrap(value,70,9);text(lines,r,y,9,'normal','right',muted);y+=lines.length*3.8+.7;}
 y=Math.max(y,leftEnd)+4;
 if(doc.projectSummary||doc.project){heading('PROJECT SUMMARY');paragraph(doc.projectSummary||doc.project,w,9);y+=2;}
 const proforma=type==='Proforma',cuts=receipt?(voucher?[m,45,112,155,r]:[m,55,155,r]):quote?[m,31,83,164,r]:proforma?[m,r]:[m,28,121,136,163,r];
 const labels=receipt?(voucher?['DATE','INFO','METHOD','AMOUNT']:['DATE','REFERENCE / METHOD','AMOUNT']):quote?['NO.','SERVICE','DESCRIPTION','PRICE']:proforma?['SERVICE DESCRIPTION']:['#','SERVICE DESCRIPTION','QTY','RATE','AMOUNT'];
 const tableHeader=()=>{ensure(17);text(receipt?(voucher?'PAYMENTS MADE':'PAYMENTS RECEIVED'):quote?'SERVICES QUOTED':type==='Proforma'?'SERVICES TO BE PROVIDED':'SERVICES PROVIDED',m,y,8.5,'bold','left',gold);y+=4;pdf.setFillColor(...ink);pdf.rect(m,y,w,8,'F');labels.forEach((label,i)=>{const left=voucher?i<3:i<2||quote&&i===2;text(label,left?cuts[i]+2:cuts[i+1]-2,y+5.3,7,'bold',left?'left':'right',[255,255,255])});y+=12;};
 tableHeader();
 const rows=receipt?(doc.payments||[]).map(p=>voucher?[p.date||'-',p.info||'Payment made',p.method||p.reference||'—',money(p.amount)]:[p.date||'-',p.reference||p.method||'Payment received',money(p.amount)]):(doc.items||[]).map((item,i)=>quote?[String(i+1).padStart(2,'0'),item.name||'-',item.description||'',item.rateText||money(item.rate)]:proforma?[[item.name,item.description].filter(Boolean).join('\n')]:[String(i+1),[item.name,item.description].filter(Boolean).join('\n'),String(item.qty??1),item.rateText||money(item.rate),money(Number(item.qty??1)*Number(item.rate||0))]);
 if(!rows.length){paragraph(receipt?'No payments recorded.':'No services recorded.');}
 for(const row of rows){let cells=row.map((v,i)=>wrap(v,cuts[i+1]-cuts[i]-4,8.5,(i===1&&(!receipt||!voucher))?'bold':'normal'));let offset=0;const count=Math.max(...cells.map(c=>c.length));while(offset<count){if(y+8>269){newPage();tableHeader();}const take=Math.min(count-offset,Math.max(1,Math.floor((269-y-3)/3.8)));cells.forEach((lines,i)=>{const leftAlign=voucher?i<3:i<2||quote&&i===2;text(lines.slice(offset,offset+take),leftAlign?cuts[i]+2:cuts[i+1]-2,y,8.5,(i===1&&(!receipt||!voucher))?'bold':'normal',leftAlign?'left':'right',i===2&&quote?muted:ink)});y+=take*3.8+1.5;rule(y);y+=4;offset+=take;if(offset<count){newPage();tableHeader();}}}
 const subtotal=(doc.items||[]).reduce((a,i)=>a+(proforma?Number(i.proformaAmount??(Number(i.qty??1)*Number(i.rate||0))):Number(i.qty??1)*Number(i.rate||0)),0),discount=subtotal*Number(doc.discount||0)/100,tax=(subtotal-discount)*Number(doc.tax||0)/100,total=subtotal-discount+tax,paid=(doc.payments||[]).reduce((a,p)=>a+Number(p.amount||0),0);
 if(quote){ensure(9);text('Tailored services are provided on request',105,y+1,10,'italic','center');y+=9;}
 else{const totals=receipt?[[voucher?'PAYMENT MADE':'PAYMENT RECEIVED',paid,true]]:proforma?[['TOTAL PROJECT VALUE',total],['ADVANCE AMOUNT REQUIRED (50%)',total*.5,true]]:[['Subtotal',subtotal],...(discount?[['Discount',-discount]]:[]),...(tax?[['GST / tax ('+Number(doc.tax)+'%)',tax]]:[]),['TOTAL DUE',total,true],...(type==='Invoice'&&paid?[['Paid',paid],['BALANCE DUE',Math.max(0,total-paid),true]]:[])];ensure(totals.length*5.5+5);y+=2;for(const [label,value,bold] of totals){const labelX=proforma?m:128;if(bold){pdf.setDrawColor(...gold);pdf.line(labelX,y-3,r,y-3)}text(label,labelX,y,9,bold?'bold':'normal','left',muted);text(money(value),r,y,bold?11:9,bold?'bold':'normal','right',bold?gold:ink);y+=5.5;}y+=3;}
 if(f.payment){const payment=[['Account Holder',b.account??'ERIC RODGERS'],['Account Number',b.accountNo??'50100486607332'],['IFSC',b.ifsc??'HDFC0000682'],['Bank / Branch',b.bank??'HDFC Bank, ALAPPUZHA'],['UPI ID',b.upi??'ericrodgers555@oksbi']].filter(([,v])=>v);if(payment.length||qr){const lines=payment.flatMap(([k,v])=>wrap(k+': '+v,118,9,'bold'));ensure(Math.max(34,lines.length*4+10));heading('PAYMENT DETAILS');const py=y;for(const line of lines){text(line,m,y,9,'bold','left',muted);y+=4;}if(qr)pdf.addImage(qr,'PNG',r-27,py-2,25,25);y=Math.max(y,py+(qr?26:0))+4;}}
 if(doc.terms){heading(receipt?(voucher?'VOUCHER NOTES':'RECEIPT NOTES'):'TERMS & CONDITIONS');for(const line of String(doc.terms).split(/\r?\n/).filter(s=>s.trim()))paragraph(line,w-4,9,'normal',m+2,muted);}
 ensure(19);y+=3;rule(y);y+=5;text(receipt?(voucher?'Payment voucher issued by Eric’s Designs.':'Thank you for your payment.'):quote?"Thank you for considering Eric's Designs.":"Thank you for choosing Eric's Designs.",quote?m:105,y,9,'italic',quote?'left':'center',muted);y+=5;if(b.email||b.phone)paragraph([b.phone,b.email].filter(Boolean).join(' | '),w,8,'normal',m,muted);
 const finalFooterY=Math.min(282,y+5);const pages=pdf.getNumberOfPages();for(let p=1;p<=pages;p++){pdf.setPage(p);const footerY=p===pages?finalFooterY:282;rule(footerY);text([b.name||"Eric's Designs",b.address].filter(Boolean).join(' - '),105,footerY+5,7,'normal','center',muted);if(pages>1)text(p+' / '+pages,r,footerY+10,7,'normal','right',muted);}
 return pdf;
}
async function asset(path){const response=await fetch(path,{cache:'no-store'});if(!response.ok)throw new Error('Document image could not be loaded. Please reload the CRM.');const blob=await response.blob();return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(blob)})}
async function file(doc,type){const jsPDF=root.jspdf?.jsPDF||(await root.loadInvoicePdfLibrary());const [logo,qr]=await Promise.all([asset('./assets/reference-document-logo.png'),FORMAT[type].payment?asset('./assets/reference-payment-qr.png'):null]);const pdf=buildPdf(doc,type,jsPDF,logo,qr);return new File([pdf.output('blob')],(doc.number||'document').replace(/[\\/:*?"<>|]/g,'-')+'.pdf',{type:'application/pdf'})}
if(typeof module!=='undefined'&&module.exports)module.exports={buildPdf,FORMAT};
if(root?.document){root.createDocumentPdf=doc=>file(doc,typeOf(doc.type));root.createInvoicePdf=doc=>file(doc,'Invoice');root.createQuotationPdf=doc=>file(doc,'Quotation');root.createProformaPdf=doc=>file(doc,'Proforma');root.createPaymentReceiptPdf=doc=>{const voucher=doc?.receiptKind==='Payment voucher';return file({...doc,type:'Receipt',terms:doc.receiptNotes||(voucher?'This voucher confirms the payment made by Eric’s Designs.':'This receipt confirms the payments listed above.'),number:(doc.number||'')+(voucher?' VOUCHER':' RECEIPT')},'Receipt')};}
})(typeof window!=='undefined'?window:globalThis);
